// App/Redux/Actions/types.js

export const FETCH_UPCOMING_MOVIES_REQUEST = 'FETCH_UPCOMING_MOVIES_REQUEST';
export const FETCH_UPCOMING_MOVIES_SUCCESS = 'FETCH_UPCOMING_MOVIES_SUCCESS';
export const FETCH_UPCOMING_MOVIES_FAILURE = 'FETCH_UPCOMING_MOVIES_FAILURE';

export const FETCH_MOVIE_TRAILER_REQUEST = 'FETCH_MOVIE_TRAILER_REQUEST';
export const FETCH_MOVIE_TRAILER_SUCCESS = 'FETCH_MOVIE_TRAILER_SUCCESS';
export const FETCH_MOVIE_TRAILER_FAILURE = 'FETCH_MOVIE_TRAILER_FAILURE';

export const FETCH_MOVIE_DETAILS_REQUEST = 'FETCH_MOVIE_DETAILS_REQUEST';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAILURE = 'FETCH_MOVIE_DETAILS_FAILURE';

export const FETCH_MOVIE_IMAGES_REQUEST = 'FETCH_MOVIE_IMAGES_REQUEST';
export const FETCH_MOVIE_IMAGES_SUCCESS = 'FETCH_MOVIE_IMAGES_SUCCESS';
export const FETCH_MOVIE_IMAGES_FAILURE = 'FETCH_MOVIE_IMAGES_FAILURE';

export const CLEAR_TRAILER = 'CLEAR_TRAILER';

// Add search action types
export const FETCH_MOVIE_SEARCH_REQUEST = 'FETCH_MOVIE_SEARCH_REQUEST';
export const FETCH_MOVIE_SEARCH_SUCCESS = 'FETCH_MOVIE_SEARCH_SUCCESS';
export const FETCH_MOVIE_SEARCH_FAILURE = 'FETCH_MOVIE_SEARCH_FAILURE';
